[package]
name = "anarhia_rdp"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
futures = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
clap = { version = "4.5.11", features = ["cargo"] }
rdp-rs = "0.1.0"
